CREATE TABLE [dbo].[master_data_crm_registrations] (
    [id] NVARCHAR(36) NOT NULL,
    [newKey] NVARCHAR(1000) NOT NULL,
    [keyForNoCRM] NVARCHAR(500) NOT NULL,
    [mainRegist] INT NOT NULL CONSTRAINT [master_data_crm_registrations_mainRegist_df] DEFAULT 1,
    [registrationTopic] NVARCHAR(500) NOT NULL,
    [soldToCode] NVARCHAR(100) NOT NULL,
    [shipToCode] NVARCHAR(100) NOT NULL,
    [endUserCode] NVARCHAR(100) NOT NULL,
    [plantCode] NVARCHAR(100) NOT NULL,
    [materialCode] NVARCHAR(100) NOT NULL,
    [onOffSpec] NVARCHAR(20) NOT NULL,
    [materialDescription] NVARCHAR(500) NOT NULL,
    [ownerName] NVARCHAR(500) NOT NULL,
    [countryName] NVARCHAR(500),
    [shipToName] NVARCHAR(500),
    [soldToName] NVARCHAR(500),
    [endUser] NVARCHAR(500),
    [groupName] NVARCHAR(500),
    [materialNameOnCoa] NVARCHAR(500),
    [additionalRequirement] NVARCHAR(1000),
    [pic] NVARCHAR(500),
    [commission] DECIMAL(18,4) NOT NULL CONSTRAINT [master_data_crm_registrations_commission_df] DEFAULT 0,
    [productDescription] NVARCHAR(1000),
    [classified] NVARCHAR(500),
    [commissionIndirect] DECIMAL(18,4) NOT NULL CONSTRAINT [master_data_crm_registrations_commissionIndirect_df] DEFAULT 0,
    [commissionFinancialDiscount] DECIMAL(18,4) NOT NULL CONSTRAINT [master_data_crm_registrations_commissionFinancialDiscount_df] DEFAULT 0,
    [newCoaName] NVARCHAR(500),
    [newTier1] NVARCHAR(500),
    [newOem] NVARCHAR(500),
    [packing] NVARCHAR(500),
    [agreedSpecType] NVARCHAR(500),
    [wasteScrap] NVARCHAR(500),
    [forResaleNotApprove] NVARCHAR(500),
    [imdsDate] NVARCHAR(100),
    [model] NVARCHAR(500),
    [approve] NVARCHAR(500),
    [partName] NVARCHAR(500),
    [coaName] NVARCHAR(500),
    [process] NVARCHAR(500),
    [application] NVARCHAR(500),
    [subApp] NVARCHAR(500),
    [zoneName] NVARCHAR(500),
    [plantName] NVARCHAR(500),
    [countryCode] NVARCHAR(100),
    [endUserExportControl] NVARCHAR(500),
    [endUserName] NVARCHAR(500),
    [productName] NVARCHAR(500),
    [priceFormula] NVARCHAR(50) NOT NULL CONSTRAINT [master_data_crm_registrations_priceFormula_df] DEFAULT 'CPL',
    [spread] DECIMAL(18,4) NOT NULL CONSTRAINT [master_data_crm_registrations_spread_df] DEFAULT 0,
    [createdBy] NVARCHAR(100) NOT NULL CONSTRAINT [master_data_crm_registrations_createdBy_df] DEFAULT 'sales-forecast-web',
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [master_data_crm_registrations_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL CONSTRAINT [master_data_crm_registrations_updatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [master_data_crm_registrations_pkey] PRIMARY KEY CLUSTERED ([id])
);

CREATE UNIQUE NONCLUSTERED INDEX [master_data_crm_registrations_newKey_key]
ON [dbo].[master_data_crm_registrations]([newKey]);

CREATE UNIQUE NONCLUSTERED INDEX [master_data_crm_registrations_keyForNoCRM_key]
ON [dbo].[master_data_crm_registrations]([keyForNoCRM]);
